### ISSUE TITLE
.yaml vs .yml

### ISSUE THREAD

**Issue by lewiuberg** [gahjelle/pyconfs#21]
Hi!

This isn't an issue, since it may be intentional, but I would just like to report my findings.
Some file formats are based on others, such as `cff`, which is based on `yaml`. I see `yml` and  `yaml` being used interchangeably. However, when I try to insert `yml` as the `file_format` in `Configuration.from_file()`, I get an error.

![Skjermbilde 2021-10-20 kl  15 31 46](https://user-images.githubusercontent.com/43423020/138103680-2a9d7d16-4b10-4f4e-b9be-b2bd2ad69f3b.png)

**Comment by gahjelle** [comment]
Right. I believe the **file format** is called YAML (YAML Ain't a Markup Language, https://yaml.org/). On the other hand,  `.yml` and `.yaml` are common **file extensions** for YAML files. 

It's possible to do something like aliases within the readers so that `file_format="yml"` could work.  But it's probably not valuable, in this case at least.

**Comment by lewiuberg** [comment]
No, in this case it is ok like it is. I just wanted to let you know since some might think it wasn't working. I read that especially windows users were scared of file extensions that wasn't of length 3 😅

You may close the issue 🙂

**Comment by gahjelle** [comment]
Thanks @lewiuberg  for digging into this.

I'll just note that both `.yml` and `.yaml` are supported as **file extensions**. In other words, both of the following will work and detect the YAML **file format** based on the file extensions:

```python
yml = Configuration.from_file("stuff.yml")
yaml = Configuration.from_file("stuff.yaml")
```

**Comment by lewiuberg** [comment]
Very Good! When I have a little more time I would like to expand the documentation/usage description if you don't mind:)

**Comment by gahjelle** [comment]
I would love it. PyConfs is tragically underdocumented at the moment 🙈

**Comment by lewiuberg** [comment]
With some input from you, i can learn, and pyconfs can get well documented, win win :) such a great library needs some documentation to show its capabilities. Please let me know If you like this style of documentation. https://github.com/lewiuberg/visual-automata
